application: kevintjahjadi
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: static/css

- url: /images
  static_dir: static/img

- url: /fonts
  static_dir: static/fonts

- url: /.*
  script: _go_app
